export const DEFAULT_COLLEGES = [
  {
    id: 'c1',
    name: 'Indian Institute of Technology Bombay',
    location: 'Powai, Mumbai, Maharashtra',
    state: 'Maharashtra',
    stream: 'Engineering',
    fees: 2.2,
    rank: 1,
    approval: 'NAAC A++',
    type: 'Deemed University',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/IITBMainBuildingCROP.jpg?width=900',
    logo: 'https://commons.wikimedia.org/wiki/Special:FilePath/IIT_Bombay_color_logo.svg?width=120',
    description: "IIT Bombay is one of India's premier engineering institutions, known for top research, strong placements and global recognition.",
    tags: ['Autonomous', 'Engineering', 'Deemed University'],
    featured: true,
    detailsUrl: '#',
    createdAt: 1700000000001
  },
  {
    id: 'c2',
    name: 'COEP Technological University',
    location: 'Shivajinagar, Pune',
    state: 'Maharashtra',
    stream: 'Engineering',
    fees: 1.5,
    rank: 21,
    approval: 'NAAC A+',
    type: 'Autonomous',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/COEP_Main_building.JPG?width=900',
    logo: '',
    description: 'One of the oldest engineering institutions in Asia with strong academics and an excellent placement culture.',
    tags: ['Autonomous', 'Engineering'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000002
  },
  {
    id: 'c3',
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    state: 'Rajasthan',
    stream: 'Engineering',
    fees: 5.3,
    rank: 26,
    approval: 'NAAC A',
    type: 'Private',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bits_Clock_tower.jpg?width=900',
    logo: '',
    description: 'A top private university known for academic flexibility, innovation and strong alumni outcomes.',
    tags: ['Private', 'Engineering'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000003
  },
  {
    id: 'c4',
    name: 'VIT Vellore',
    location: 'Vellore, Tamil Nadu',
    state: 'Tamil Nadu',
    stream: 'Engineering',
    fees: 3.9,
    rank: 11,
    approval: 'NAAC A++',
    type: 'Private',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/VIT_University_Main_Building.jpg?width=900',
    logo: '',
    description: 'Highly reputed private university with strong industry collaborations and outcomes.',
    tags: ['Private', 'Engineering'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000004
  },
  {
    id: 'c5',
    name: 'IIIT Hyderabad',
    location: 'Gachibowli, Hyderabad',
    state: 'Telangana',
    stream: 'Engineering',
    fees: 3.2,
    rank: 42,
    approval: 'NAAC A',
    type: 'Deemed University',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/IIIT_Hyderabad_-_Academic_block.jpg?width=900',
    logo: '',
    description: 'Leading institute for AI and Computer Science research with excellent research output and placements.',
    tags: ['AI & CS', 'Engineering'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000005
  },
  {
    id: 'c6',
    name: 'NIT Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    state: 'Tamil Nadu',
    stream: 'Engineering',
    fees: 1.4,
    rank: 9,
    approval: 'NAAC A+',
    type: 'Government',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/NIT_Trichy_-_Main_Building.jpg?width=900',
    logo: '',
    description: 'One of the top NITs with strong academics, campus culture and impressive placements.',
    tags: ['Government', 'Engineering'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000006
  },
  {
    id: 'c7',
    name: 'XLRI - Xavier School of Management',
    location: 'Jamshedpur, Jharkhand',
    state: 'Jharkhand',
    stream: 'Management',
    fees: 24,
    rank: 5,
    approval: 'NAAC A+',
    type: 'Autonomous',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/XLRI_Jamshedpur_Front_Gate.jpg?width=900',
    logo: '',
    description: 'A prestigious management school with decades of legacy and strong industry relationships.',
    tags: ['Autonomous', 'Management'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000007
  },
  {
    id: 'c8',
    name: 'Manipal Academy of Higher Education',
    location: 'Manipal, Karnataka',
    state: 'Karnataka',
    stream: 'Medical',
    fees: 8.5,
    rank: 7,
    approval: 'NAAC A+',
    type: 'Deemed University',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Manipal_University_Main_Building.jpg?width=900',
    logo: '',
    description: 'Top health science university with modern hospitals and globally recognized programs.',
    tags: ['Medical', 'Deemed University'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000008
  },
  {
    id: 'c9',
    name: 'National Law School of India University',
    location: 'Bengaluru, Karnataka',
    state: 'Karnataka',
    stream: 'Law',
    fees: 2.7,
    rank: 1,
    approval: 'NAAC A++',
    type: 'Government',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/National_Law_School_of_India_University,_Bengaluru.jpg?width=900',
    logo: '',
    description: 'A benchmark for legal education in India and a top destination for CLAT toppers.',
    tags: ['Government', 'Law'],
    featured: false,
    detailsUrl: '#',
    createdAt: 1700000000009
  }
];
